name: CI for Flask App

on:
  push:
    branches:
      - main  # Replace with the name of your main branch if different
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run database migrations
        run: |
          flask db upgrade

      - name: Run tests
        env:
          DATABASE_URL: mysql+pymysql://root:password@127.0.0.1:3306/testdb
        run: |
          pytest --maxfail=5 --disable-warnings
