name: Packer Build

on:
  pull_request:
    paths:
      - "packer/packer.pkr.hcl"

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2
        with:
            version: 1.11.2

      - name: Install Packer Plugins
        run: |
          mkdir -p ~/.packer.d/plugins
          curl -Lo ~/.packer.d/plugins/packer-plugin-amazon-ebs https://releases.hashicorp.com/packer-plugin-amazon-ebs/1.1.0/packer-plugin-amazon-ebs_1.1.0_linux_amd64.zip
          unzip ~/.packer.d/plugins/packer-plugin-amazon-ebs -d ~/.packer.d/plugins/

      - name: Force Format File
        run: packer fmt packer/packer.pkr.hcl

      - name: Run Packer Format Check
        id: packer_fmt
        run: |
          packer fmt -check packer/packer.pkr.hcl || exit 1

      - name: Validate Packer Template
        run: packer validate packer/packer.pkr.hcl

      - name: Build Packer AMI (Only on Merge)
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        id: build-ami
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          packer build packer/packer.json | tee packer-output.log
          AMI_ID=$(grep -oP '(ami-[a-zA-Z0-9]+)' packer-output.log | tail -1)
          echo "::set-output name=ami_id::$AMI_ID"

      - name: Store AMI ID in GitHub Secrets
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh secret set PACKER_AMI_ID -b "${{ steps.build-ami.outputs.ami_id }}"
