
name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var "ami_id=${{ secrets.PACKER_AMI_ID }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "ami_id=${{ secrets.PACKER_AMI_ID }}"
